# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  # Use the codecov Orb
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      # Node 11 Image
      - image: circleci/node:11

    working_directory: ~/gatsby-background-image

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - run: cd integration && yarn install && cd ..

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run the tests and upload coverage data to codecov
      - run: yarn test:update --collectCoverage=true
      - store_artifacts:
          path: coverage

      - codecov/upload:
          file: coverage/coverage-final.json